### ISSUE TITLE
增加校园网统计信息显示

### ISSUE THREAD

**Issue by kenvix** [mzdluo123/TimeTableBot#15]
http://202.207.177.111:888/z-ud/optMonitorInfo

或许可以集成到ttb？

![image](https://user-images.githubusercontent.com/4546175/99510648-4a303680-29c2-11eb-97fe-7778f7813831.png)

![FR~64)OG7)XL$KK81T)_8DG](https://user-images.githubusercontent.com/4546175/99510616-43092880-29c2-11eb-84aa-a57ae434bc35.png)

他的统计甚至非常详细，wifi认证方式都分类了

**Comment by mzdluo123** [comment]
在做了在做了
